- name: Remove ShieldBuntu jail config
  ansible.builtin.file:
    path: "{{ fail2ban_jail_file }}"
    state: absent

- name: Stop and disable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: false
    state: stopped
  failed_when: false
