galaxy_info:
  role_name: firewall
  author: shieldbuntu
  description: UFW-based firewall hardening
  license: TBD
  min_ansible_version: '2.16'
  platforms:
  - name: Ubuntu
    versions:
    - noble
