- name: Apply ShieldBuntu sysctl parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ kernel_sysctl_file }}"
    state: present
    reload: true
    sysctl_set: true
  loop: "{{ kernel_sysctl_values | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
