galaxy_info:
  role_name: tor-blocking
  author: shieldbuntu
  description: Block inbound traffic from the public Tor exit node list
  license: TBD
  min_ansible_version: '2.16'
  platforms:
  - name: Ubuntu
    versions:
    - noble
