ssh_config_file: /etc/ssh/sshd_config
ssh_backup_file: /etc/ssh/sshd_config.shieldbuntu-bak

ssh_settings:
  PermitRootLogin: "no"
  PasswordAuthentication: "no"
  KbdInteractiveAuthentication: "no"
  X11Forwarding: "no"
  AllowAgentForwarding: "no"
  AllowTcpForwarding: "no"
  MaxAuthTries: "3"
  MaxSessions: "4"
  ClientAliveInterval: "300"
  ClientAliveCountMax: "0"
  LoginGraceTime: "60"
  IgnoreRhosts: "yes"
  HostbasedAuthentication: "no"
  PermitEmptyPasswords: "no"
  PermitUserEnvironment: "no"
  Banner: "/etc/issue.net"
  LogLevel: "VERBOSE"
  UsePAM: "yes"
  Protocol: "2"
  Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com"
  KexAlgorithms: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256"
  HostKeyAlgorithms: "ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256"
