galaxy_info:
  role_name: unused-packages
  author: shieldbuntu
  description: Remove orphaned and unused packages
  license: TBD
  min_ansible_version: '2.16'
  platforms:
  - name: Ubuntu
    versions:
    - noble
