galaxy_info:
  role_name: grub-password
  author: shieldbuntu
  description: Password-protect GRUB so unattended boot params can't be edited
  license: TBD
  min_ansible_version: '2.16'
  platforms:
  - name: Ubuntu
    versions:
    - noble
