galaxy_info:
  role_name: auto-updates
  author: shieldbuntu
  description: Enable unattended security updates
  license: TBD
  min_ansible_version: '2.16'
  platforms:
  - name: Ubuntu
    versions:
    - noble
