galaxy_info:
  role_name: clamav
  author: shieldbuntu
  description: ClamAV antivirus with refreshed signatures
  license: TBD
  min_ansible_version: '2.16'
  platforms:
  - name: Ubuntu
    versions:
    - noble
