galaxy_info:
  role_name: audit
  author: shieldbuntu
  description: auditd with a baseline ruleset
  license: TBD
  min_ansible_version: '2.16'
  platforms:
  - name: Ubuntu
    versions:
    - noble
