galaxy_info:
  role_name: no-exec
  author: shieldbuntu
  description: noexec/nosuid/nodev mount hardening for ephemeral filesystems
  license: TBD
  min_ansible_version: '2.16'
  platforms:
  - name: Ubuntu
    versions:
    - noble
